instasaver_user_en_homepage:
    path:     /id{id_num}
    defaults: { _controller: InstasaverUserEnBundle:UserEn:index }
    requirements: 
        id_num: \d+ 

test_controller_en:
    path: /testing
    defaults: { _controller: InstasaverUserEnBundle:Test:index }

instasaver_user_en_edit:
    path: /editProfile
    defaults: { _controller: InstasaverUserEnBundle:UserEn:editProfile }

instasaver_user_en_get_cur_lang:
   path: /getCurLang
   defaults: { _controller: InstasaverUserEnBundle:UserEn:getCurrentLang }

instasaver_user_en_change_pass:
   path: /changePass
   defaults: { _controller: InstasaverUserEnBundle:UserEn:changePass }

instasaver_user_en_upload_avatar:
  path: /uploadavatar
  defaults: { _controller: InstasaverUserEnBundle:UserEn:uploadAvatar }